server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  rabbitmq:
    host: 101.200.201.14
    port: 5672
    username: root
    password: WuLiao.112
mybatis:
  mapper-locations: classpath*:com/xc/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


redis:
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  blockWhenExhausted: true
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  jmxEnabled: true
  redisHost: 101.200.201.14
  redisPort: 6379
  redisPassword: WuLiao.112
  timeout: 1000


resetpassword:
  timeout: 60
